CREATE TABLE GUA_LOG_PROPRIETARIA (
    LOG_ID INT PRIMARY KEY,
    LOG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    OPERATION VARCHAR(10),
    USER_NAME VARCHAR(30)
);

CREATE TABLE GUA_LOG_USUARIO (
    LOG_ID INT PRIMARY KEY,
    LOG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    OPERATION VARCHAR(10),
    USER_NAME VARCHAR(30)
);

CREATE TABLE GUA_LOG_LOCALIZACAO (
    LOG_ID INT PRIMARY KEY,
    LOG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    OPERATION VARCHAR(10),
    USER_NAME VARCHAR(30)
);

CREATE TABLE GUA_LOG_PARQUE_EOLICO (
    LOG_ID INT PRIMARY KEY,
    LOG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    OPERATION VARCHAR(10),
    USER_NAME VARCHAR(30)
);

CREATE TABLE GUA_LOG_TORRE (
    LOG_ID INT PRIMARY KEY,
    LOG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    OPERATION VARCHAR(10),
    USER_NAME VARCHAR(30)
);

CREATE TABLE GUA_LOG_AEROGERADOR (
    LOG_ID INT PRIMARY KEY,
    LOG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    OPERATION VARCHAR(10),
    USER_NAME VARCHAR(30)
);

CREATE TABLE GUA_LOG_SENSOR_RAIOS (
    LOG_ID INT PRIMARY KEY,
    LOG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    OPERATION VARCHAR(10),
    USER_NAME VARCHAR(30)
);

CREATE TABLE GUA_LOG_SENSOR_CLIMA (
    LOG_ID INT PRIMARY KEY,
    LOG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    OPERATION VARCHAR(10),
    USER_NAME VARCHAR(30)
);

CREATE TRIGGER 